---
language: node_js
node_js:
  - "6"

cache:
  yarn: true

env:
  - PACKAGE=core
  - PACKAGE=renderer
  - PACKAGE=hir
  - PACKAGE=text-renderer
  - PACKAGE=react-renderer
  - PACKAGE=commonmark-renderer
  - PACKAGE=contenttype-html
  - PACKAGE=contenttype-markdown

before_install:
  - npm install -g lerna
  - npm install -g ember-cli

install:
  - lerna bootstrap
  - lerna run build-tests

script: pushd packages/$PACKAGE; npm test
