---
language: node_js
node_js:
  - "6"

cache:
  yarn: true

env:
  - PACKAGE=core
  - PACKAGE=hir
  - PACKAGE=renderer-hir
  - PACKAGE=renderer-plain-text
  - PACKAGE=renderer-react
  - PACKAGE=renderer-commonmark
  - PACKAGE=contenttype-html
  - PACKAGE=contenttype-commonmark
  - PACKAGE=coverage

install:
  - yarn
  - ./node_modules/lerna/bin/lerna.js bootstrap

script:
  - if $PACKAGE == coverage; ./node_modules/jest/bin/jest.js --coverage; else; ./node_modules/jest/bin/jest.js packages/$PACKAGE; fi
