---
language: node_js
node_js:
  - "8"

env:
  global:
    - CC_TEST_REPORTER_ID=cf897ba2cdf052230767ba43b61026729790d3db38a4e8693134464087be410e

install:
  - npm ci

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run lint
  - npm run typecheck
  - npm test -- --no-cache --coverage --maxWorkers=4
  - pushd packages/\@atjson/renderer-commonmark/
  - time node ./performance/index.js
  - popd

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
