name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install
      run: |
        npm ci
    - name: 🔎 ESLint
      run: |
        npm run lint
    - name: 🃏 Jest
      run: |
        npm run test
    - name: ✅ Type Check
      run: |
        npm run typecheck
  perf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: 🐢 Performance
      run: |
        npm ci
        npm run typecheck
        npm run perf
